### PR TITLE
Target 0.11.0 in CI

### PR DESCRIPTION
**Pull request by nitinprakash96**
Drops version < 0.11.0 from CI.

### CODE REVIEW

**Comment by nitinprakash96** [comment]
The CI failure seems unrelated to the code? Is there some way to re-run that?

**Comment by aeronavery** [comment]
When I merged #14 I noticed CI was having issues unrelated to the changes. I reran the CI for this pull request and looks like it passed. I'm not sure what's going on.

**Comment by nitinprakash96** [comment]
> I'm not sure what's going on.

CI failed for every job except 1 because the code on `master` was able to compile only with `v0.11.0`. I removed v0.9 and 0.10 from CI as the language has breaking changes now.

**Comment by aeronavery** [comment]
I understood why those ones failed but the CI for zig master kept getting canceled somehow, unless that's by design. Anyway, seems all fixed now. As always, thank you for the patch!

**Comment by nitinprakash96** [comment]
> CI for zig master kept getting canceled somehow

Oh sorry I misunderstood. 😅 

> As always, thank you for the patch!

Always a pleasure :)

**Pull request merged**
